------------------------------------------------------------------------------
-- PROGRAMME: CRÉATION DES TABLE DE LA BASE DE DONNÉES DE WEB TROUVE_TOUT    -
-- ÉQUIPE: GABRIEL BOMBARDIER, JUSTIN DUGAS                                  -
-- RÉALISÉ PAR: GABRIEL BOMBARDIER                                           -
-- PROJET: B-63 PROJET FINAL                                                 -
------------------------------------------------------------------------------

-- SUPPRESSION DES TABLES --
DROP TABLE TAB_USER CASCADE CONSTRAINT;
DROP TABLE TAB_CATEGORIE CASCADE CONSTRAINT;
DROP TABLE TAB_ADRESSE CASCADE CONSTRAINT;
DROP TABLE TAB_ARTICLE CASCADE CONSTRAINT;
DROP TABLE TAB_RABAIS CASCADE CONSTRAINT;

--CRÉATION DES TABLES --
CREATE TABLE TAB_USER (
	ID_USER NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	ID_ADRESSE NUMBER,
	PRENOM VARCHAR2(30) NOT NULL,
	NOM VARCHAR2(30) NOT NULL,
	SEXE VARCHAR2(1) NOT NULL,
	AGE NUMBER(2),
	EMAIL VARCHAR2(60) NOT NULL,
	PASSWORD VARCHAR2(30) NOT NULL
);

CREATE TABLE TAB_CATEGORIE (
	ID_CAT NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	NOM varchar2(40) UNIQUE
);

CREATE TABLE TAB_ADRESSE (
	ID_ADRESSE NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	NUMERO NUMBER(6),
	RUE varchar2(40),
	VILLE varchar2(40),
	CODE varchar2(7),
	PAYS varchar2(40)
);

CREATE TABLE TAB_ARTICLE (
	ID_ARTICLE NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	ID_RABAIS NUMBER, 
	ID_CAT NUMBER, 
	NOM varchar2(40),
	ART_DESCRIPTION varchar2(100),
	PRIX_BASE NUMBER(10,2),
	PRIX_COURANT NUMBER(10,2),
	EN_RABAIS varchar2(1)
);

CREATE TABLE TAB_RABAIS (
	ID_RABAIS NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	POURCENTAGE NUMBER(2),
	DATE_DEBUT DATE,
	DATE_FIN DATE
);

-- AJOUTER LES FOREIGN KEYS --
ALTER TABLE TAB_USER ADD CONSTRAINT user_fk0 FOREIGN KEY (ID_ADRESSE) REFERENCES TAB_Adresse(ID_ADRESSE);
ALTER TABLE TAB_ARTICLE ADD CONSTRAINT article_fk0 FOREIGN KEY (ID_RABAIS) REFERENCES TAB_Rabais(ID_RABAIS);
ALTER TABLE TAB_ARTICLE ADD CONSTRAINT article_fk1 FOREIGN KEY (ID_CAT) REFERENCES TAB_Categorie(ID_CAT);


